### ISSUE TITLE
Project Dollhouse dont work 64 bit windows xp because only SP2 İ cant download SP3 

### ISSUE THREAD

**Issue by acuc44** [Afr0Games/Project-Dollhouse#109]
And Net Framework cant update because Only SP2 SP1    windows tp 64 bit

Solve this problem please :):)

**Comment by Matriks404** [comment]
isnt 64-bit xp based on Windows Server 2003? It has only 2 SP's.

**Comment by ZackCDLVI** [comment]
Yes. A bulk of applications built for Windows XP and above can run at a minimum of Service Pack 2. Unfortunately, .NET isn't one of them. I wish it wasn't the case.
