### ISSUE TITLE
Inbox doesn't remove people from dropdown list if they go offline or crash.

### ISSUE THREAD

**Issue by Blayer98** [Afr0Games/Project-Dollhouse#121]
This can happen...

![image](https://cloud.githubusercontent.com/assets/6663677/5892867/c6688072-a4c6-11e4-83a7-7ba44686aba4.png)

**Comment by Afr0** [comment]
Yeah, I looked into that, and the list shouldn't be behaving that way. o_O
Not sure why it does.
