### ISSUE TITLE
Boot any remaining online clients that are connected to the map view back onto the SAS screen.

### ISSUE THREAD

**Issue by Blayer98** [Afr0Games/Project-Dollhouse#122]
Otherwise, this happens and the client crashes, this isn't exactly important, but it's something to think about. :)
![upload_2015-1-25_21-8-56](https://cloud.githubusercontent.com/assets/6663677/5893334/e98ffcfe-a4d7-11e4-99ba-e28495f4be80.png)

**Comment by Afr0** [comment]
Uhm, what?
Please explain the problem better!

**Comment by Blayer98** [comment]
What I'm saying is, In the picture, While I was still online, the network code crashed.

The game should display a Message saying:
"Lost server connection. Possible causes: your client may have erroneously disconnected or the server may have crashed."
Then once the User presses OK, the game then goes back onto the SAS Screen.

**Comment by ZackCDLVI** [comment]
Returning to the SAS should be easy to implant since you only need to disconnect from the city server while telling the client to return to the last game screen.

**Comment by Afr0** [comment]
This was a server issue. Disconnected clients weren't being properly removed.
