### ISSUE TITLE
Fix hilariously stupid license comments

### ISSUE THREAD

**Issue by RHY3756547** [Afr0Games/Project-Dollhouse#128]
Our codebase is now pretty impressive, apart from this hilarious, grammatically incorrect and unneccessary comment at the top of nearly every file:

>The Original Code is the TSOClient.
>
>The Initial Developer of the Original Code is
>ddfczm. All Rights Reserved.
>
>Contributor(s): ______________________________________.

Listing the initial developer of the code doesn't make any sense when multiple people are contributing to the code. This looks like a trend that was started back in the SimsLib days (i'd like to blame nicholas but it might not have even been him), before anyone really knew what they were doing.

The solution would be to reduce this to a simple MPL header as follows:

```
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
```

Might be a bit harder to do than a simple Find In Files, @ZackCDLVI . ;)

**Comment by ZackCDLVI** [comment]
> Might be a bit harder to do than a simple Find In Files, @ZackCDLVI . ;)

First get rid of the repetitive lines such as *"Contributor(s): ______________________________________."* and *"The Initial Developer of the Original Code is"*. Then you can focus on the lines that have are less repetitive, such as *The Original Code is the [namespace].*

**Comment by RHY3756547** [comment]
Please don't randomly close issues when they are unresolved.

**Comment by Afr0** [comment]
Zack upgraded all the files in the client to Mozilla 2,0, so I assumed it was resolved.

**Comment by RHY3756547** [comment]
That happened before this issue was created, I believe.

**Comment by ZackCDLVI** [comment]
I upgraded the licenses but I never took out the rest.
