### ISSUE TITLE
Make use of Compile Time hashtags

### ISSUE THREAD

**Issue by descention** [Afr0Games/Project-Dollhouse#133]
https://github.com/Afr0/Project-Dollhouse/blob/master/Other/libs/CityDataModel/CityDataModel/Logger.cs#L46

This function can be modified to use "#if DEBUG" and "#endif". Doing so removes the need for the configuration file completely.

https://msdn.microsoft.com/en-us/library/4y6tbswk.aspx

**Comment by ZackCDLVI** [comment]
This would definitely be the efficient approach. The server would be easiest to implant but the client I'm not so sure about due to Rhy's upcoming buy mode merge.
