### ISSUE TITLE
Invalid blend value 'InvSrcAlpha' while Compiling

### ISSUE THREAD

**Issue by RShadowhand** [Afr0Games/Project-Dollhouse#134]
Forked, cloned, fixed a lot of issues that rose, but this one stumped me.

I'm getting:
* Invalid blend value 'INVSRCALPHA' in \TSOClient\tso.client\Content\Effects\2DWorldBatch.fx in tso.contentProj

I'm pretty sure I've got all the dependencies, and they are all right.

**Comment by Afr0** [comment]
Hmmm... I didn't write any of the shaders, so you'll have to wait for @RHY3756547 to respond, but... did you install Windows Phone SDK 7?

**Comment by Afr0** [comment]
Also, the city renderer is currently experiencing issues on newer nVidia cards, but I believe 2DWorldBatch is for the general renderer.

**Comment by RShadowhand** [comment]
I do have MonoGame and XNA Studio 4.0 installed.
I think I will wait for @RHY3756547 
Thank you for such swift response.

**Comment by RHY3756547** [comment]
Cant answer this fully right now, just make sure you're building the content with the monogame pipeline, and use Monogame 3.2.

**Comment by Afr0** [comment]
If you're on Windows, make sure you're compiling against the WindowsGL version of Monogame. If you're on any non-Windows OS, none of the code's been tested and quite frankly we'd be happy if you could make it work.

**Comment by RShadowhand** [comment]
I've got MonoGame 3.2, and honestly, I've got no idea how to make it so that it's compiled against WindowsGL. I will do a bit of research and then get back to you. About the other OS stuff, I might just clone it to one of my VPSes and see if I can do anything. Brb.

**Comment by Afr0** [comment]
The folder where you installed Monogame should have different folders... one of them should be named WindowsGL. The DLL you want to compile against is in there. Use "Browse" when adding references to the project.

**Comment by RShadowhand** [comment]
I actually just changed the content processor to "Effect - XNA Framework" on the problematic files, and then it compiled without a problem.

Now tso.client.exe says "Error TSO was not found on your system". Does this mean I need to get TSO from EA?

**Comment by Afr0** [comment]
Yup, it does. See NIOTSO.org

Date: Tue, 7 Apr 2015 07:22:15 -0700
