### ISSUE TITLE
House do not reload when trying to create a new GameScreen

### ISSUE THREAD

**Issue by francot514** [Afr0Games/Project-Dollhouse#141]
I just want to comment this bug i have noticed when testing for blueprint houses, trying to move from house to another by creating different game screen

**Comment by Afr0** [comment]
Uhm... I'm not sure I understand what you mean. :/

**Comment by RHY3756547** [comment]
This isn't a bug- it's more that we haven't implemented this yet. Game screens will be switchable when it becomes relevant, ie. when saving lot state is implemented

**Comment by francot514** [comment]
But the bug is, that when you create new screen it attach to the old one and create a ugly lot screen, with not clean borders check the image: http://i62.tinypic.com/9vgsh2.jpg

**Comment by RHY3756547** [comment]
Generally, problems caused by modifying code are not bugs for the original program. This isn't a public API- once a solution for this is ready you should use that instead.

**Comment by francot514** [comment]
Ok but the problem occurs even when no modifying code, you can test it...

**Comment by Fanobii** [comment]
Doesn't happen to me...  You sure it's not one of your code changes, or do you have steps to reproduce the bug?

**Comment by RHY3756547** [comment]
You kind of have to modify the code to create a new screen in the first place. The current 3D scene setup is admittedly a mess - I'm not sure why scenes aren't tied to screens so that they can be removed, but it's something that I'll get around to eventually.

**Comment by Fanobii** [comment]
Sorry, I didn't realise that you had to modify the code.  My mistake.
