### ISSUE TITLE
Last Session username not stored locally

### ISSUE THREAD

**Issue by LetsRaceBwoi** [Afr0Games/Project-Dollhouse#144]
This should be a pretty easy fix; when the user successfully logs in, the login.ini file in the root of the TSOClient directory needs to be written to, which should contain the last username used to log in.

**Comment by RHY3756547** [comment]
Bingo, though it might be a better idea to use the PD config ini just to keep things centralised.

**Comment by LetsRaceBwoi** [comment]
Agreed.
