### ISSUE TITLE
More Simantics Research

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#145]
Research requires knowledge of modding The Sims. All notes may be posted on [nioTSO's Wiki](wiki.niotso.org) or the [Project Dollhouse forums](http://forum.afr0games.com/), preferably in the Contribute topic. But it's important to hand this information over to Rhys too. Every detail counts. You may need to install vanilla TS1 along side your existing copy since it may still have debugging features that later taken out in later expansions. Please review [SimAntics & World Development](http://forum.afr0games.com/index.php?threads/simantics-world-development.181/) before continuing.

**Comment by RHY3756547** [comment]
Should we really be using an issue tracker to state something this general and obvious? A better format for this and other such general design requirements would be a roadmap.

You don't have to make issues for the sake of making issues.

**Comment by ZackCDLVI** [comment]
Just be happy I made it up for grabs.

**Comment by RHY3756547** [comment]
Did you even read what I said?

**Comment by ZackCDLVI** [comment]
Yes. I did you favour.

**Comment by RHY3756547** [comment]
Right. What I wanted to hear was your take on why this should be on our issue tracker despite being incredibly general, unassignable and obvious. Seeing as you dodged the implication twice, I'm going to assume you don't have a good answer.

This would be better mentioned on a wiki page, such as one detailing practices to follow when performing simantics research, such as verifying and reporting all findings to the simantics wiki before implementing the changes in the game, and providing object examples and cases to test with along with the pull request. Obviously linked to from a "hub" page, showing our roadmap for the various areas of the project.

**Comment by ZackCDLVI** [comment]
OF course, you close

**Comment by LetsRaceBwoi** [comment]
:angry: Didn't I ask you two to stop arguing?

**Comment by RHY3756547** [comment]
If you want to reopen this, address my points.

**Comment by ZackCDLVI** [comment]
The best way to encourage someone is to put it "up for grabs." Now stop trying to control me. We're a fucking team.

**Comment by ZackCDLVI** [comment]
I'm sick and tired of this tug of war.

**Comment by RHY3756547** [comment]
Genuine concerns: still not addressed...

**Comment by ZackCDLVI** [comment]
This is childish. Replies deleted.

**Comment by RHY3756547** [comment]
You just deleted my reason for closing this without addressing it. If you keep doing this, I'll have to remove you from the organisation.

Just for reference (why this should be on our issue tracker):
* Too general for an issue, like making an issue called "add features"
* Unassignable
* No completion criteria 
* Much more suitable on a roadmap or wiki page, with technical info and guidelines included

**Comment by ZackCDLVI** [comment]
Welcome to my world.

**Comment by RHY3756547** [comment]
You didn't even read what i said, I literally saw you reopen this live 5s after I posted the message. Please consider what I'm saying.

**Comment by ZackCDLVI** [comment]
> Please consider what I'm saying.

Please consider what I'M saying. I'm not gonna telling what you want to hear but you need to hear. If you want to add a roadmap and guidelines, then be my guest. I'm only providing a foundation. Use it.

**Comment by RHY3756547** [comment]
So you agree this shouldn't be an issue, right? It's not like closing it erases it from existance, The whole of the single paragraph can serve as a "base" while it's closed.

Either way, this is your final warning. Reason why this should be an issue, or don't reopen it.

**Comment by ZackCDLVI** [comment]
This should be an issue. It is issue. The lack of full SimAnatics engine **is** an issue.

**Comment by RHY3756547** [comment]
OK, 6 times is enough. You've been removed from the organisation so you can't keep reopening this without explaining yourself. If you can give a real reason why this should be a "GitHub Issue", not just that it's an english "issue", I will reopen this for you.

**Comment by robinkooli** [comment]
My email is full of notifications from this thread.
I need to unwatch this project :/

**Comment by RHY3756547** [comment]
Sorry. It has been dealt with now, probably...

**Comment by ZackCDLVI** [comment]
I've wanted this to end yesterday.
