### ISSUE TITLE
SimAntics Research

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#146]
Research requires knowledge of modding The Sims. All notes may be posted on [nioTSO's Wiki](wiki.niotso.org) or the [Project Dollhouse forums](http://forum.afr0games.com/), preferably in the Contribute topic. But it's important to hand this information over to Rhys too. Every detail counts. You may need to install vanilla TS1 along side your existing copy since it may still have debugging features that later taken out in later expansions. Please review [SimAntics & World Development](http://forum.afr0games.com/index.php?threads/simantics-world-development.181/) before continuing.

**Comment by RHY3756547** [comment]
Spamming our issue tracker with identical issues will get you banned. Please do not do this again without providing any reasoning.

**Comment by ZackCDLVI** [comment]
You've left me no other option. I've given you plenty of reasons that you refuse to accept because it's not what you want to hear.

**Comment by RHY3756547** [comment]
You only provided one reason after repoening the issue 5 times. "This is a problem, thus it is an 'issue' thus it belongs on the issue tracker" is flawed reasoning, considering that github issues are actually "tickets" and are set up to be completable and assignable units of work, which is their main benefit. You did not provide any other reasons when I claimed that it was insufficient.

**Comment by LetsRaceBwoi** [comment]
This practically does but at the same time does not belong on the issue tracker; it is a valid issue, but Rhys is right, GH Issues are mainly used as tickets.  It all depends on how the owner - in this case, Afr0 - wants to use Issues.

**Comment by KenBeanNet** [comment]
Can you all shut up about this?  I want to be apart of this git, but this conversation is pointless.

**Comment by Afr0** [comment]
I don't want to take sides in this quarrel, though I do agree that the issue was a bit general...

Date: Tue, 16 Jun 2015 10:22:29 -0700

**Comment by ZackCDLVI** [comment]
Suit yourselves. But questions have been in an Github issue tracker too.
