### ISSUE TITLE
Gray screen after Maxis logo

### ISSUE THREAD

**Issue by LetsRaceBwoi** [Afr0Games/Project-Dollhouse#148]
For a split second (less than 100ms) there is a gray screen shortly after the Maxis logo has been shown on the current build.  I might work on fixing this myself, but it looks like it's not loading the relevant files in time which causes a short delay.  It annoys me a little but I could live with it, but really it should be loading while the Maxis logo is shown the optimise the client.

**Comment by Afr0** [comment]
Yeah, I know, this is one of those issues that me or Rhys just won't prioritize. But go ahead and fix it :)

**Comment by RHY3756547** [comment]
The UI tends to draw screens before they've been properly prepared a lot. I'll look into this some time later, but it probably won't be soon.
