### ISSUE TITLE
Cannot logout or return to select a sim screen

### ISSUE THREAD

**Issue by LetsRaceBwoi** [Afr0Games/Project-Dollhouse#149]
Features need implementing.

**Comment by Afr0** [comment]
Please be more specific?

**Comment by LetsRaceBwoi** [comment]
When you click on the option to logout when you've clicked the exit button in the SAS screen or clicked the "Return to Select-A-Sim Screen" button in the options whilst in the City View, it displays a message stating that "This feature is not implemented yet!"

**Comment by ZackCDLVI** [comment]
A modified or new options dialog would need to be created to support logging out of the game or to SAS with obvious network calls needed to be included. Possibly why it hasn't been implanted yet. Go back to the login menu would be easy but SAS would probably cause problems if someone attempts to do it from the already offline debug lot.

**Comment by RHY3756547** [comment]
Yes, this is a more difficult problem. The city view doesn't really know if it's online or not at the moment, which is one problem, but there's also the problem of reverting to connecting to the login server, back out of the city.
