### ISSUE TITLE
Roads should be enabled server-side

### ISSUE THREAD

**Issue by LetsRaceBwoi** [Afr0Games/Project-Dollhouse#152]
This way, servers will have greater control over cities and plot placement.  Roads could also be placed by the server.

**Comment by RHY3756547** [comment]
Roads in the original game were placed in the spaces between tiles, thus they did not affect lot placement afaik, but may have affected lot price. I'm not sure what you mean here, but we'll probably allow sending custom road maps from the server at some point in the far future.

**Comment by LetsRaceBwoi** [comment]
Yes, that was what I meant.
