### ISSUE TITLE
Bmp bitmap should be saved in container??

### ISSUE THREAD

**Issue by francot514** [Afr0Games/Project-Dollhouse#154]
Just for general easy access modification to the bmp chunk data, a bitmap property that allow easy access for avoid use of extra streams...

**Comment by Afr0** [comment]
Not sure exactly which container you're talking about, but the way it's like that is most likely to save memory.

Date: Wed, 24 Jun 2015 17:41:52 -0700

**Comment by francot514** [comment]
I mean create bitmap property to avoid need to read chun data stream each time, that way you can export or reuse it again..

**Comment by Afr0** [comment]
Hm, I see what you mean. Why don't you do that yourself? It shouldn't be hard. When you're done, either submit a pull request or post the code on the wiki, and I will add it :)

Date: Thu, 25 Jun 2015 12:31:17 -0700

**Comment by francot514** [comment]
Ok nevermind, it had to be changed in all tso client code for better usage, and that means rewrite a lot of code for loading spf files and other...
