### ISSUE TITLE
1px or so difference in the Lot name / City name at the top of the screen

### ISSUE THREAD

**Issue by LetsRaceBwoi** [Afr0Games/Project-Dollhouse#157]
![image](https://cloud.githubusercontent.com/assets/12881812/8436599/55a5e662-1f51-11e5-8306-f00ec20e1c0f.png)
Grr.  My OCD doesn't like this.
I'll look in to fixing it.

**Comment by RHY3756547** [comment]
Probably to do with an image not drawing using integer start/end bounds. See the UIGameTitle class, which is the specific use, but the real problem is somewhere in UIImage, specifically with the 9 slice mode.
