### ISSUE TITLE
SimBox disables Z-buffer for drawing (solution: move to render target)

### ISSUE THREAD

**Issue by tomascw** [Afr0Games/Project-Dollhouse#160]
![](http://i.imgur.com/JnehAnZ.png) ![](http://i.imgur.com/yW3dJQF.png)
Not the best title in the world. Sorry. I dunno how to properly explain this error, so here are some screenshots.

**Comment by LetsRaceBwoi** [comment]
Isn't this the same as [this](http://forum.afr0games.com/index.php?threads/character-head-bug-not-sure-if-known.545/)?

**Comment by ZackCDLVI** [comment]
Oh, my bad. Well, I'll get the shotgun so Rhys can blow my brains out.

**Comment by LetsRaceBwoi** [comment]
No, it was never reported here like it should have been; good call.
