### ISSUE TITLE
Map view expecting Live Mode?

### ISSUE THREAD

**Issue by ZackCDLVI** [Afr0Games/Project-Dollhouse#166]
![](http://i.imgur.com/Gb0tkzL.png)
![](http://i.imgur.com/JRRCs7b.png)

**Comment by LetsRaceBwoi** [comment]
There needs to be a static public variable in the GameController which specifies if NoNetwork (lot debug) is on, and that should disable this from happening.

**Comment by ZackCDLVI** [comment]
Issue has been fixed in merge #167.

**Comment by RHY3756547** [comment]
I didn't even tell anyone I fixed this...
