### ISSUE TITLE
I  downloaded  TSO but..

### ISSUE THREAD

**Issue by acuc44** [Afr0Games/Project-Dollhouse#169]
I downloaded tso but error Disc Label 2.
I remove tso setup and I setup again but disc label 2 error again
After I Downloaded new TSO setup and I setup again But same error

Why?

**Comment by RHY3756547** [comment]
This is an issue with the TSO setup, not PD. I'm not even sure why it happens? What OS are you on?

**Comment by acuc44** [comment]
My OS is Windows 7 ultimate 32 bit

**Comment by Blayer98** [comment]
Try deleting the entire setup and all the files, then re-download it again?

**Comment by acuc44** [comment]
I re download again, again and again after ı deleted sims online downloader and all setup files and ı re download all but dont work after ı deleted all and  I re download all but  :(
