### ISSUE TITLE
Crash - Windows 7 32bit with intel 965 chipset

### ISSUE THREAD

**Issue by quarter187** [Afr0Games/Project-Dollhouse#185]
I have tried everything i could possibly find for a solution yet no matter what i do project dollhouse and FreeSO continues to crash with this error. Perhapz the gpu juzt wont run them i am trully obsessed with playing tso. Iz there anything that can be done?
![image](https://cloud.githubusercontent.com/assets/15954402/11317829/9b37b726-8ff1-11e5-9ce3-289f7238aa80.jpg)

**Comment by LetsRaceBwoi** [comment]
project dollhouse is abandoned, use [this](https://github.com/RHY3756547/FreeSO/issues) instead
